Реализовал запросы к БД в рамках проекта по бронированию
alozhka/travelline_practice pull request #7
Opened 2024-04-14 20:24 UTC by alozhka

2024-05-04 14:50 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        phone_number NVARCHAR(11) NOT NULL,
Тут вопрос, точно ли 11, вроде бы [есть](https://www.quora.com/What-is-maximum-and-minimum-length-of-any-mobile-number-across-the-world) номера длиннее. Ты, получается, брал из расчета на местный номер? В требованиях про это ничего нет, просто интересно узнать твою позицию)

2024-05-04 15:18 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT AK_room_number UNIQUE (room_number)
Точно называем ограничения в таком формате?
На лекции видел пример формата `PK_<название таблицы>_<название столбца>`
Сделаем по аналогии с этим?

2024-05-04 15:20 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT PK_room_id PRIMARY KEY (room_id),
Формат `PK_<название таблицы>_<название столбца>`

2024-05-04 15:20 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT PK_customer_id PRIMARY KEY (customer_id)
Формат `PK_<название таблицы>_<название столбца>`

2024-05-04 15:20 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT PK_booking_id PRIMARY KEY (booking_id),
Формат `PK_<название таблицы>_<название столбца>`

2024-05-04 15:20 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT FK_booking_customer
Формат `FK_<название таблицы>_<название столбца>`

2024-05-04 15:20 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT FK_booking_room
Формат `FK_<название таблицы>_<название столбца>`

2024-05-04 15:21 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT PK_facility_id PRIMARY KEY (facility_id)
Формат `PK_<название таблицы>_<название столбца>`

2024-05-04 15:21 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT PK_facility_id PRIMARY KEY (facility_id)
Формат `PK_<название таблицы>_<название столбца>`

2024-05-04 15:22 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT PK_room_to_facility PRIMARY KEY (room_id, facility_id),
Формат `PK_<название таблицы>_<название столбца>_<название столбца>`

2024-05-04 15:24 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT FK_rooms_to_facilities_room
Формат `FK_<название таблицы>_<название столбца>`

2024-05-04 15:24 UTC, pklgn commented on SQL/queries/initial/initial_create.sql
> +        CONSTRAINT FK_rooms_to_facilities_facility
Формат `FK_<название таблицы>_<название столбца>`

2024-05-04 15:37 UTC, pklgn commented on SQL/queries/initial/tables_filling.sql
> +    (110, N'одноместный c балконом', $3.6, 1),
Почему решил вставлять значения со знаком валюты?

2024-05-04 15:39 UTC, pklgn commented on SQL/queries/task/1.sql
> +    AND
`AND` можно в конце строки предыдущей оставить.

2024-05-04 15:50 UTC, pklgn commented on SQL/queries/task/1.sql
> +    booking b ON b.room_id = r.room_id
Не будет ли эффективнее вычислить сначала занятые на сегодня номера, а потом через NOT IN вывести свободные?
Вычислить занятые можно через подзапрос.
Для сравнения эффективности можно воспользоваться планировщиком запросов в MSSQL.

2024-05-04 15:56 UTC, pklgn commented on SQL/queries/task/3.sql
> +GROUP BY
Почему так сложно?) Зачем столько `JOIN`'ов? Для чего, кроме кастомера, столько таблиц нужно? Зачем `GROUP BY`?

2024-05-04 16:09 UTC, pklgn commented on SQL/queries/task/4.sql
> +    c.phone_number = '79377777777'
Может в задании имелся в виду номер номера `room_number`?

2024-05-04 16:09 UTC, pklgn commented on SQL/queries/task/4.sql
> +GROUP BY
Зачем эти `GROUP BY`?)

2024-05-04 16:52 UTC, pklgn commented on SQL/queries/task/5.sql
> +GROUP BY
Мне кажется, нужно пересмотреть подход к написанию запросов. Убрать лишние JOIN'ы и группировку. Для проверки брони номера по дате нужны только таблицы брони и номера.

2024-05-04 17:30 UTC, pklgn requested changes
Нужно переделать в первую очередь запросы на выборку, не совсем уловил идею с `GROUP BY`.

2024-05-10 10:21 UTC, alozhka commented on SQL/queries/initial/initial_create.sql
> +        phone_number NVARCHAR(11) NOT NULL,
Я брал стандартный номер по типу +1 (234) 567 89 01
Получается 11 цифр без плюса

2024-05-10 10:30 UTC, alozhka commented on SQL/queries/initial/tables_filling.sql
> +    (110, N'одноместный c балконом', $3.6, 1),
Чтобы точно закрепить цену за валютой. Вдруг мы захотим держать цену не от доллара, а от рубля, например. 
Если мы будем работать на американский рынок, а цена будет в рублях, то будут частые колебания цен из-за изменчивости курса

2024-05-10 17:09 UTC, alozhka commented on SQL/queries/task/3.sql
> +GROUP BY
Я это делал для группировки объектов (вайфай и прочее) в номере, чтобы выводить их одной строкой. У нас же связующая таблица для них.

2024-05-10 17:59 UTC, alozhka commented on SQL/queries/task/4.sql
> +GROUP BY
Для вывода объектов вместе с комнатой. Я буду выводить всё, кроме них

2024-06-01 17:00 UTC, closed without merging