Реализовал инструменты
alozhka/travelline_practice pull request #8
Opened 2024-05-07 14:51 UTC by alozhka

2024-05-07 14:51 UTC, alozhka commented
2 задание пока ещё делаю, 1 задание сделал

2024-05-12 11:38 UTC, LehaIvanov commented on lab-tools/src/actions.ts
> +	try {
Оставил [комментарий по поводу try...catch](https://t.me/c/1901556386/205), лучше оставить один - обернуть одну строчку [program.parse()](https://github.com/alozhka/travelline_practice/blob/cb08ff3c99f598e2a7af47131c80a1b7d25d8ef8/lab-tools/src/lab-tools.ts#L16), которая является точкой запуска.

2024-05-12 11:42 UTC, LehaIvanov commented on lab-tools/src/actions.ts
> +const handleError = (e: unknown): void => {
Эту функция бессмысленна, так как `console.error` преобразует переданный аргумент в строку, то есть вызов `console.error(e)` выведет валидное сообщение об ошибке. Достаточно в теле `catch` просто вызвать `console.error(e)`.

2024-05-12 11:46 UTC, LehaIvanov commented on lab-tools/src/actions.ts
В `actions` находится логика парсинга html и вычисления разницы междy json-объектами, хотя это совершенно не связанная логика. Необходимо actions.ts разбить на файлы.

2024-05-12 11:55 UTC, LehaIvanov commented on lab-tools/src/actions.ts
> +	newValue?: any
У нас был [слайд о том, что any лучше использовать](https://docs.google.com/presentation/d/16Ls6sQVChkdARkd46UfwadnsXNQ4XZTSTtQ0ug2Snh4/edit#slide=id.g1ff32486192_0_258). В данном случае можно спокойно обойтись `unknown`

2024-05-12 12:34 UTC, LehaIvanov requested changes

2024-05-12 12:34 UTC, LehaIvanov commented on lab-tools/src/actions.ts
> +		let secondJson: JsonParseData = JSON.parse(fs.readFileSync(secondJsonFileName, { encoding: 'utf8' }))
В лекции говорилось, что нужно использовать `const`, если это возможно. `firstJson` и `secondJson` можно объявить через `const`.

В [стартовом проекте](https://github.com/LehaIvanov/1-lab-tools) подключен eslint, который бы вам сообщил об этой проблеме.

2024-05-12 12:34 UTC, LehaIvanov commented on lab-tools/src/actions.ts
> +		console.log(Array.from(hrefsSet))
Наша цель - научиться писать чистые функции, `console.log` делает side effect - выводит текст в консоль, поэтому нужно вынести его выше. Данная функция просто возвращает результат парсинга, а вывод результата  в консоль должен происходить в функции, которая вызывает `handleHtmlParse`. После исправления имя функции нужно поменять на более походящее под её логику.

2024-05-12 12:34 UTC, LehaIvanov commented on lab-tools/src/actions.ts
> +		console.log(jsonDiff)
Наша цель - научиться писать чистые функции, console.log делает side effect - выводит текст в консоль, поэтому нужно вынести его выше. Данная функция просто возвращает результат сравнения, а вывод результата в консоль должен происходить в функции, которая вызывает `handleJsonDifference`. После исправления имя функции нужно поменять на более походящее под её логику.

2024-05-12 12:34 UTC, LehaIvanov commented on lab-tools/src/actions.ts
> +		}
Стараемся писать функционально:

1. в этом `for` у нас происходит преобразование одной коллекции в другую, для этого в JS есть [метод map](https://learn.javascript.ru/array-methods#map)
2. чтобы исключить `undefined`, можно использовать [filter](https://learn.javascript.ru/array-methods#filter)
3. чтобы в коллекции были только уникальные элементы, можно использовать Set (как вы и сделали), конструктор Set принимает массив.

2024-05-14 20:39 UTC, LehaIvanov commented on lab-tools/src/actions/json-diff.ts
> +function findJsonDifference(oldJson: Record<string, unknown>, newJson: Record<string, unknown>): Record<string, Difference> {
Слишком сложный алгоритм получился, давайте подскажу как упростить

1. С помощью [Object.keys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) можно получить ключи у объекта (массив в `JS` это тоже объект, к нему тоже можно применить `Object.keys`)
2. Лучше объединить ключи `oldJson` и `newJson` в один массив и пробегаться по нему
3. Чтобы узнать объект ли значение или нет лучше использовать Type Guard `const isObject = (value: unknown): value is JsonParseData => typeof value === `object` && value !== null;`
4. Для построения результата нам достаточно 3 проверки:
- Если оба значения являются объектами, то производим рекурсивный вызов
- Если `oldJson[key] === undefiend`, то новое значение
- Если `newJson[key] === undefined`, то значение удалено
- И по остаточному признаку остаётся проверка значений по ссылке `oldJson[key] === newJson[key] ? 'unchanged' : 'changed'`

2024-05-14 20:39 UTC, LehaIvanov commented on lab-tools/src/actions/json-diff.ts
> +function findJsonDifference(oldJson: Record<string, unknown>, newJson: Record<string, unknown>): Record<string, Difference> {
Не должно быть отдельной функции для массива, `areSimpleObject` тоже не должно быть, `findJsonDifference` и `findObjectDifference` по сути должны объединиться в одну функцию

2024-05-14 20:39 UTC, LehaIvanov commented on lab-tools/src/actions/json-diff.ts
> +				differences[key] = findObjectDifference(oldJson[key] as Record<string, unknown>,
Приведение типов с помощью `as` стараемся не делать, а что бы их не делать используем https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

2024-05-20 19:37 UTC, LehaIvanov commented on lab-tools/src/actions/json-diff.ts
> +				newValue: newValue
Просто, чтобы вы тоже знали: если имя ключа совпадает с названием переменной, то ключ можно не указывать. Тут получится следующим образом:

```
differences[key] = {
  type: oldJson[key] === newJson[key] ? 'unchanged' : 'changed',
  oldValue,
  newValue
}
```

В других местах тоже лучше поправить.

2024-05-20 19:37 UTC, LehaIvanov commented on lab-tools/src/actions/json-diff.ts
> +			differences[key] = {
Мутировать объект - не хорошо, поэтому лучше в подобных местах создавать новый объект на основе старого объекта.

Больше я замечаний не вижу. ДЗ засчитываю.

2024-05-21 16:03 UTC, LehaIvanov commented
Все хорошо! Замечаний нет)

2024-05-22 08:02 UTC, merged